### ISSUE TITLE
New to C#, would like to implement in Powershell

### ISSUE THREAD

**Issue by robesmithjr** [beakdan/NeoPixelUsbBridge#1]
Hello,

I was taking a look at porting your code over to Powershell in order to easily be able to add more effects.  I am making progress with capturing the output from the data being sent through the serial port with portmon, but am still discovering the values. Do you have the values for pure Red, Green and Blue by any chance?
I was wondering if there were any plans to add more effects?  I have a few FTDI232R boards, want to have a script or program to send solid colors, staggered or chase (thanks for the tip on inverting the output by reprogramming the device).  I was able to add a few prompts at the start for comport to use, # of pixels, delay, etc.  It would be awesome to have some additional effects. 

Any additional info on what the values equate to (sent out the port) would be helpful.  Certainly willing to collaborate, but my C# coding skills are not that great.

Thanks,

Rob

**Comment by beakdan** [comment]
Wow. I totally forgot about completing the next part where I connect the
pixels in a matrix with Jinx... I have some free time to complete that if
you have some patience...
Results are here https://youtu.be/sjLBjdJMUG4
And I'm actually more comfortable with power shell maybe I can help you...

Thank you for taking the time to write me

**Comment by robesmithjr** [comment]
Awesome!  So, after the initial set up (inverting the TX pin, etc.), I can send randomly generated strings to a single pixel (figure I would start there, based on the way that the 2811 controller truncates the stream).

Here is what I have so far.  Essentially, I am looking to define some constants for the common color palette (red, green, blue, cyan, yellow, orange). Maybe a couple a few others, turn pairs of lights on and off (great for Halloween!).  I am using a strand of 50 pixels that have the 2811 controller separate form the pixel. 

This code generates a random text stream and writes it to the pixel.  
--------------------------
[System.IO.Ports.SerialPort]::getportnames()
$port= new-Object System.IO.Ports.SerialPort COM4,3000000,None,7,one
$port.open()

$total=50000000 # run until we get bored and break

for($i = 0; $i -lt $total; $i++){
$code=-join ((0..127) + (50..122)| Get-Random -Count 8 | % {[char]$_})

#It might be easier to work with defined Hex Codes
    $code
    $port.write($code);$i;sleep 2
    $port.write("[[[[[[[[") #turns off #1
    sleep 1
}

$port.close()

**Comment by robesmithjr** [comment]
Wow! I took a look at the link with Jinx and that is awesome!  I would love to see this!

**Comment by beakdan** [comment]
@robesmithjr I migrate the "core" of the C# code to PowerShell. To do efects you have to fill a colors buffer and "translate" it to the bit stream expected by the pixels. This sample shows a single color for the whole array. Since I'm using the CP2102N I can drive 2048 pixels... Other USB to serial can drive a maximum of 512 pixels. Just change $pixelCount accordingly... The explanation of how it works [is here](https://adanbucio.net/2017/07/31/how-to-drive-neopixels-from-a-pc-without-a-microcontroller/)...

```
$colorWheelGRB = 
    0x00FF00, #Red
    0x7FFF00, #Orange
    0xFFFF00, #Yellow
    0xFF7F00, #Spring Green
    0xFF0000, #Green
    0xFF007F, #Turquoise
    0xFF00FF, #Cyan
    0x7F00FF, #Ocean
    0x0000FF, #Blue
    0x007FFF, #Violet
    0x00FFFF, #Magenta
    0x00FF7F; #Raspberry

$lookup = [byte]0x5b, [byte]0x1b, 
          [byte]0x53, [byte]0x13,
          [byte]0x5a, [byte]0x1a,
          [byte]0x52, [byte]0x12;

function TranslateColors([int[]]$colors, [byte[]]$uart) {
    for ($i = 0; $i -lt $colors.Length; $i++){
        $color = $colors[$i];
        $offset = $i * 8; #Eight bytes per pixel
		
        #using PS 2 so I don't have bit shift operators... using division instead
        $uart[$offset] = $lookup[[Math]::Floor($color / 2097152) -band 0x07];
        $uart[$offset + 1] = $lookup[[Math]::Floor($color / 262144) -band 0x07];
        $uart[$offset + 2] = $lookup[[Math]::Floor($color / 32768) -band 0x07];
        $uart[$offset + 3] = $lookup[[Math]::Floor($color / 4096) -band 0x07];
        $uart[$offset + 4] = $lookup[[Math]::Floor($color / 512) -band 0x07];
        $uart[$offset + 5] = $lookup[[Math]::Floor($color / 64) -band 0x07];
        $uart[$offset + 6] = $lookup[[Math]::Floor($color / 8) -band 0x07];
        $uart[$offset + 7] = $lookup[$color -band 0x07];
    }
}

$pixelCount = 2048;
[int[]]$colorBuffer = @(0) * $pixelCount;
[byte[]]$uartBuffer = @(0) * $pixelCount * 8;

$port= New-Object System.IO.Ports.SerialPort "COM8",3000000,None,7,One;
$port.Open();

$total = 10000

for($i = 0; $i -lt $total; $i++){
    $color = $colorWheelGRB[(Get-Random -Minimum 0 -Maximum 12)] #[$i % 12];
    for($p = 0; $p -lt $pixelCount; $p++) {
        $colorBuffer[$p] = $color;
    }
    
    TranslateColors -colors $colorBuffer -UartData $uartBuffer;
    
    #Use BaseStream to allow to send any character, not only text chars
    $port.BaseStream.Write($uartBuffer, 0, $uartBuffer.Length);
    $port.BaseStream.Flush();
    
    sleep 1;
}

$port.close();
```

**Comment by robesmithjr** [comment]
Hello Adan,

Thanks for porting it over, I had to make a few changes to get it to run properly under Powershell 5.1 (removed the semicolons after each line, variable for the uart data is 'uartbuffer'.  I have a decent amount of experience with Powershell (systems administration and middleware).  I found yours and Josh's explanation of how the data is inserted into the data buffer for the right timings (brilliant!).  Code is below, I will be adding some additional functions. 

I look forward to seeing the Jinx integration, that would be super! 

Rob

--------------------
$colorWheelGRB = 
    0x00FF00, #Red
    0x7FFF00, #Orange
    0xFFFF00, #Yellow
    0xFF7F00, #Spring Green
    0xFF0000, #Green
    0xFF007F, #Turquoise
    0xFF00FF, #Cyan
    0x7F00FF, #Ocean
    0x0000FF, #Blue
    0x007FFF, #Violet
    0x00FFFF, #Magenta
    0x00FF7F; #Raspberry

$lookup = [byte]0x5b, [byte]0x1b, 
          [byte]0x53, [byte]0x13,
          [byte]0x5a, [byte]0x1a,
          [byte]0x52, [byte]0x12;

function TranslateColors([int[]]$colors, [byte[]]$uart) {
    for ($i = 0; $i -lt $colors.Length; $i++){
        $color = $colors[$i];
        $offset = $i * 8; #Eight bytes per pixel
        #$uart=@()
		
        #using PS 2 so I don't have bit shift operators... using division instead
        $uartbuffer[$offset] = $lookup[[Math]::Floor($color / 2097152) -band 0x07]
        $uartbuffer[$offset + 1] = $lookup[[Math]::Floor($color / 262144) -band 0x07]
        $uartbuffer[$offset + 2] = $lookup[[Math]::Floor($color / 32768) -band 0x07]
        $uartbuffer[$offset + 3] = $lookup[[Math]::Floor($color / 4096) -band 0x07]
        $uartbuffer[$offset + 4] = $lookup[[Math]::Floor($color / 512) -band 0x07]
        $uartbuffer[$offset + 5] = $lookup[[Math]::Floor($color / 64) -band 0x07]
        $uartbuffer[$offset + 6] = $lookup[[Math]::Floor($color / 8) -band 0x07]
        $uartbuffer[$offset + 7] = $lookup[$color -band 0x07]
    }
}

$pixelCount = 3; #make this a parameter
[int[]]$colorBuffer = @(0) * $pixelCount
[byte[]]$uartBuffer = @(0) * $pixelCount * 8

$port= New-Object System.IO.Ports.SerialPort "COM16",3000000,None,7,One #COM Port should also be a parameter
$port.Open()

$total = 10000 #flash 10000 times

for($i = 0; $i -lt $total; $i++){
    $color = $colorWheelGRB[(Get-Random -Minimum 0 -Maximum 12)] #[$i % 12];
    for($p = 0; $p -lt $pixelCount; $p++) {
        $colorBuffer[$p] = $color
    }
    
    TranslateColors -colors $colorBuffer -UartData $uartBuffer
    
    #Use BaseStream to allow to send any character, not only text chars
    $port.BaseStream.Write($uartBuffer, 0, $uartBuffer.Length)
    $port.BaseStream.Flush()
    
    sleep 1
}

$port.close()

**Comment by robesmithjr** [comment]
Adan,

I posted your initial script back in the comments, but am also coding some additional effects and functions and will post it when finished. I noticed that some of the color codes need tweaking, I am using the pixels with a separate 2811 controller sealed in epoxy.

I would love to hear more about Jinx integration! 

Thank you for your work on this.

Rob
