### ISSUE TITLE
Only 1 LED lights up, green color

### ISSUE THREAD

**Issue by TheNewJavaman** [beakdan/NeoPixelUsbBridge#3]
Only one LED powers on, it's green. Any ideas as to why this error may be happening to me?

**Comment by beakdan** [comment]
I answered your question on my article:

> Please ensure that you inverted the TX signal with the FTDI utility. You could also start with a different Baud rate, acceptable values are 2000000, 2400000, 3000000.
> Try from lower to higher. I have found leds that work with baud rates as low as 1200000. So try to use leds from the same manufacturer…

I forgot to mention that I had issues with all the FT232R uart modules that I have. Turns out those were counterfeit parts and apparently there are lot of fake parts in the market. I ordered a new adapter from a reliable source but its actually the most expensive UART compared with others that support the needed baud rate (> 2Mbps), 
So, make sure that you have an original part if you use FTDI chips. The external inverter solution is actually cheaper even if you use an IC inverter, but make sure that is a high speed one as the 74HCT family.

**Comment by TheNewJavaman** [comment]
It turns out that I forgot to bridge the ground connections between my 232r and the LED strip's power supply. I bought two different 232r's on Amazon and both were genuine chips that could invert properly. Thank you so much for your help!

**Comment by beakdan** [comment]
> It turns out that I forgot to bridge the ground connections between my 232r and the LED strip's power supply. I bought two different 232r's on Amazon and both were genuine chips that could invert properly. Thank you so much for your help!

Excelent! How many leds do you have?
Since you're using the FT232R, check the direct API. With it you can control more than 512 leds. I went up as high as 2048 without glitches, but obviously a slower refresh / frame rate.

**Comment by TheNewJavaman** [comment]
So far I have 150 working. When I'm finished, I'll probably buy another three strips, totalling to 600 LEDs. Do you still have the direct API code? I'd like to take a look at it.

**Comment by TheNewJavaman** [comment]
By the way, I'm working an a program to sync audio data (music levels) to the LEDs. Would you like me to message you if I post the code on GitHub?

**Comment by beakdan** [comment]
> By the way, I'm working an a program to sync audio data (music levels) to the LEDs. Would you like me to message you if I post the code on GitHub?

Yes, I would like to see that. I'll check my archives on the weekend for the direct API version. I can't believe 2 years have passed since I published this initially and never made the time to publish the rest of the project!

**Comment by TheNewJavaman** [comment]
@beakdan I'm getting glitches as low as 150 LEDs. Do you think the direct API would fix that issue because it could prevent the bit stream from being interrupted as compared to the VCP drivers?

**Comment by beakdan** [comment]
> @beakdan I'm getting glitches as low as 150 LEDs. Do you think the direct API would fix that issue because it could prevent the bit stream from being interrupted as compared to the VCP drivers?

150 leds are within the capabilities of the drivers. The exact limit being 512 leds. And you wont see glitches on the first 512 but instead on any led after that.
So I guess it could be a wiring problem or maybe you need a bigger power supply... A simple way to test this is to reduce the light intensity by right shifting the bytes to send one or two bits. If the glitches disappear with dimmer light then you absolutely need a more capable power source.
Assuming that the 150 leds are with white color at full brightes the power supply should be able to handle 45 watts.

**Comment by beakdan** [comment]
Also... try with lower baud rates... Although the spec sounds like the protocol is time sensitive, it actually is very forgiving about the timings as long as it doesn't detect a reset signal.
So try first with 2Mbps. And up from there: 2.4Mbps and 3Mbps. The closer value to the specs is 2.4Mbps assuming that you have the WS2812. The SK6812 can actually go faster than that and it handles nicely the 3Mbps.

**Comment by TheNewJavaman** [comment]
Lower baud rates fixed it! 2.4mbs is the way to go for my WS2812B strips.
I also finished the music visualizer application: [https://github.com/TheNewJavaman/synesthesia](https://github.com/TheNewJavaman/synesthesia)

**Comment by beakdan** [comment]
> Lower baud rates fixed it! 2.4mbs is the way to go for my WS2812B strips.
> I also finished the music visualizer application: https://github.com/TheNewJavaman/synesthesia

It looks awsome! I'm glad it worked!
